# Generated by Django 2.0.6 on 2018-06-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('name', models.CharField(max_length=20, verbose_name='username')),
                ('email', models.EmailField(max_length=254, verbose_name='mail')),
                ('address', models.CharField(max_length=100, verbose_name='address')),
                ('message', models.CharField(max_length=500, verbose_name='message')),
                ('object_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'user leave message',
            },
        ),
    ]
